version: '2.1'

services:

  cesium:
    build:
      context: .
      args:
        CESIUM_VERSION: 1.47
        PORT: 8088
      dockerfile: Dockerfile
    image: sofwerx/cesium
    container_name: cesium
    hostname: cesium
#    volumes:
#      - ./AgileMeridian:/cesium/AgileMeridian
    ports:
      - 8088:8088

